CREATE TABLE `Account` (
  `accountID` varchar(32) NOT NULL DEFAULT '',
  `accountType` smallint(5) unsigned DEFAULT NULL,
  `notifyEmail` varchar(128) DEFAULT NULL,
  `speedUnits` tinyint(3) unsigned DEFAULT NULL,
  `distanceUnits` tinyint(3) unsigned DEFAULT NULL,
  `volumeUnits` tinyint(3) unsigned DEFAULT NULL,
  `economyUnits` tinyint(3) unsigned DEFAULT NULL,
  `temperatureUnits` tinyint(3) unsigned DEFAULT NULL,
  `latLonFormat` tinyint(3) unsigned DEFAULT NULL,
  `geocoderMode` tinyint(3) unsigned DEFAULT NULL,
  `privateLabelName` varchar(32) DEFAULT NULL,
  `isBorderCrossing` tinyint(4) DEFAULT NULL,
  `retainedEventAge` int(10) unsigned DEFAULT NULL,
  `autoAddDevices` tinyint(4) DEFAULT NULL,
  `expirationTime` int(10) unsigned DEFAULT NULL,
  `defaultUser` varchar(32) DEFAULT NULL,
  `password` varchar(32) DEFAULT NULL,
  `contactName` varchar(64) DEFAULT NULL,
  `contactPhone` varchar(32) DEFAULT NULL,
  `contactEmail` varchar(128) DEFAULT NULL,
  `timeZone` varchar(32) DEFAULT NULL,
  `passwdQueryTime` int(10) unsigned DEFAULT NULL,
  `lastLoginTime` int(10) unsigned DEFAULT NULL,
  `isActive` tinyint(4) DEFAULT NULL,
  `displayName` varchar(40) DEFAULT NULL,
  `description` varchar(128) DEFAULT NULL,
  `notes` text,
  `lastUpdateTime` int(10) unsigned DEFAULT NULL,
  `creationTime` int(10) unsigned DEFAULT NULL,
  `veerReport` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `gprsInterval` int(10) NOT NULL DEFAULT '300',
  `crmTenant` varchar(45) DEFAULT 'farjadsystem',
  `smsPack` int(10) DEFAULT '0',
  `last_daily_backup_time` int(10) DEFAULT '1498293058',
  `data_life_in_day` int(2) DEFAULT '186',
  PRIMARY KEY (`accountID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
