CREATE TABLE `Device` (
  `accountID` varchar(32) NOT NULL DEFAULT '',
  `deviceID` varchar(32) NOT NULL DEFAULT '',
  `groupID` varchar(32) DEFAULT NULL,
  `equipmentType` varchar(40) DEFAULT NULL,
  `vehicleID` varchar(24) DEFAULT NULL,
  `vehicleType` smallint(6) unsigned DEFAULT NULL,
  `uniqueID` varchar(40) DEFAULT NULL,
  `deviceCode` varchar(24) DEFAULT NULL,
  `deviceType` varchar(24) DEFAULT NULL,
  `expirationTime` timestamp NULL DEFAULT '2030-01-01 00:00:00',
  `pushpinID` varchar(32) DEFAULT NULL,
  `serialNumber` varchar(24) DEFAULT NULL,
  `simPhoneNumber` varchar(24) DEFAULT NULL,
  `imeiNumber` varchar(24) DEFAULT NULL,
  `temperatureIndex` smallint(6) DEFAULT '0',
  `ignitionIndex` smallint(6) DEFAULT '5',
  `codeVersion` varchar(32) DEFAULT NULL,
  `featureSet` varchar(64) DEFAULT NULL,
  `ipAddressValid` varchar(128) DEFAULT NULL,
  `lastTotalConnectTime` int(10) unsigned DEFAULT NULL,
  `lastDuplexConnectTime` int(10) unsigned DEFAULT NULL,
  `pendingPingCommand` text,
  `lastPingTime` int(10) unsigned DEFAULT NULL,
  `totalPingCount` smallint(5) unsigned DEFAULT NULL,
  `supportsDMTP` tinyint(4) DEFAULT NULL,
  `supportedEncodings` tinyint(3) unsigned DEFAULT NULL,
  `unitLimitInterval` smallint(5) unsigned DEFAULT NULL,
  `maxAllowedEvents` smallint(5) unsigned DEFAULT NULL,
  `totalProfileMask` blob,
  `totalMaxConn` smallint(5) unsigned DEFAULT NULL,
  `totalMaxConnPerMin` smallint(5) unsigned DEFAULT NULL,
  `duplexProfileMask` blob,
  `duplexMaxConn` smallint(5) unsigned DEFAULT NULL,
  `duplexMaxConnPerMin` smallint(5) unsigned DEFAULT NULL,
  `ipAddressCurrent` varchar(32) DEFAULT NULL,
  `remotePortCurrent` smallint(5) unsigned DEFAULT NULL,
  `lastInputState` varchar(32) DEFAULT '0,0,0,0,0',
  `lastValidLatitude` double DEFAULT NULL,
  `lastValidLongitude` double DEFAULT NULL,
  `lastGPSTimestamp` int(10) unsigned DEFAULT NULL,
  `lastOdometerKM` double DEFAULT '0',
  `lastGeozoneID` varchar(256) DEFAULT NULL,
  `isActive` tinyint(4) DEFAULT NULL,
  `displayName` varchar(40) DEFAULT NULL,
  `description` varchar(128) DEFAULT NULL,
  `notes` text,
  `smsEmail` varchar(45) DEFAULT NULL,
  `lastUpdateTime` int(10) unsigned DEFAULT NULL,
  `creationTime` int(10) unsigned DEFAULT NULL,
  `lastStatusCode` int(10) DEFAULT NULL,
  `lastAddress` varchar(256) DEFAULT NULL,
  `engineRuntime` int(10) unsigned DEFAULT '0',
  `odometerOffset` int(10) DEFAULT '0',
  `rmto` int(1) unsigned DEFAULT '0',
  `pasmand` int(1) unsigned DEFAULT '0',
  `shiftCheck` int(1) DEFAULT '0',
  `shiftStartTime` int(6) DEFAULT '480',
  `shiftEndTime` int(6) DEFAULT '1020',
  `calcVehicleWorkTime` tinyint(4) DEFAULT '0',
  `vehicleWorkTime` int(10) DEFAULT '0',
  `vehicleWorkTimeOffset` int(10) DEFAULT '0',
  `timeInterval` smallint(5) unsigned DEFAULT '120',
  `digitalInputMask` varchar(64) DEFAULT '0,0,0,0,0',
  `digitalInputNotifyMask` varchar(32) DEFAULT '0,0,0,0,0',
  `analogInputMask` varchar(64) DEFAULT '0,0',
  `smsEmailNotify` varchar(32) DEFAULT '0,0',
  `lastDigitalInputState` varchar(32) DEFAULT '0,0,0,0,0',
  `lastAnalogInputValue` varchar(64) DEFAULT '0.0,0.0',
  `digIn1Mask` int(6) DEFAULT NULL,
  `digIn2Mask` int(6) DEFAULT NULL,
  `digIn3Mask` int(6) DEFAULT NULL,
  `digIn4Mask` int(6) DEFAULT NULL,
  `digIn5Mask` int(6) DEFAULT NULL,
  `analogIn1Mask` int(6) DEFAULT NULL,
  `analogIn2Mask` int(6) DEFAULT NULL,
  `digIn1Value` varchar(1) DEFAULT '0',
  `digIn2Value` varchar(1) DEFAULT '0',
  `digIn3Value` varchar(1) DEFAULT '0',
  `digIn4Value` varchar(1) DEFAULT '0',
  `digIn5Value` varchar(1) DEFAULT '0',
  `analogIn1Value` double DEFAULT '0',
  `analogIn2Value` double DEFAULT '0',
  `alarmMask` varchar(128) DEFAULT '64787,64817',
  `alarmNotifyMask` varchar(32) DEFAULT '1,1',
  `dIn1HourTime` int(10) unsigned DEFAULT '0',
  `dIn2HourTime` int(10) unsigned DEFAULT '0',
  `dIn3HourTime` int(10) unsigned DEFAULT '0',
  `dIn4HourTime` int(10) unsigned DEFAULT '0',
  `wt_effective_timestamp` int(10) DEFAULT NULL,
  `SMS_LOGIN` varchar(45) DEFAULT NULL,
  `SMS_PASS` varchar(45) DEFAULT NULL,
  `CONFIG_KEY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`accountID`,`deviceID`),
  KEY `altIndex` (`uniqueID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
